site_name: "Narayan’s Knowledge Library"
theme:
  name: material

nav:
  - Home: index.md
  - AI:
      - Transformers: ai/transformers.md
      - LangChain Tricks: ai/langchain-tricks.md
  - Fullstack:
      - Python: python/python.md
      - FastAPI Logging: fullstack/fastapi-logging.md
      - React Performance: fullstack/react-performance.md
  - System Design:
      - Cache Strategies: system-design/cache-strategies.md
  - Timeline:
      - August 2025 Week 3: timeline/2025-08-week3.md
